import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Urbanist } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { NavbarLp } from "@/components/landingPage/navbar";
import AnimatedCursor from "@/components/all/cursur";
import LiquidCircleCursor from "@/components/all/cursur";
import SmoothScroll from "@/providers/lenis-provider";

const urbanist = Urbanist({
  variable: "--font-heading",
  subsets: ["latin"],
  display: "swap",
});

// Manrope → For body text
const manrope = Manrope({
  variable: "--font-body",
  subsets: ["latin"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${manrope.variable} antialiased`}

      >
         <NavbarLp /> 
        <LiquidCircleCursor />
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
